import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import Header from './_components/Header';
import { headers } from 'next/headers';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={inter.className + 'bg-black h-auto w-[100%] header-white'}>
        <Header />
        {children}
      </body>
    </html>
  );
}
